### PR TITLE
fix Uncaught ReferenceError: WebViewBridgeAndroid is not defined

### PR DESCRIPTION
**Pull request by magicismight**
fix bug: [#71](https://github.com/alinz/react-native-webview-bridge/issues/71)
```
[INFO:CONSOLE(1)] "Uncaught ReferenceError: WebViewBridgeAndroid is not
defined", source: (1)
```

### CODE REVIEW

**Comment by Bhullnatik** [comment]
I tried to implement this this way too, but it wasn't working strangely...
Does everything work for you? I see you removed the `root.reload()` too, it should be necessary to use the javascript interface as per the docs (See #66 )

**Comment by magicismight** [comment]
Everthing works fine for me,you can test it in your project.
I don`t think root.reload is necessary.
Because the webview haven`t be loaded at that point,but I`m not sure about this.

**Comment by magicismight** [comment]
@Bhullnatik 
At first it works wired too.
It will send message multiple times after the component is unmounted and mounted again.
But I found out it is because in javascript DeviceEventEmitter didn`t remove everytime the component is unmounted.

**Comment by malinthe** [comment]
Seems to work!

**Comment by erikatg** [comment]
had the same problem, got fixed by this fix.

**Comment by aa900031** [comment]
It wasn't working by me, either
how to fix it !?

**Comment by foloinfo** [comment]
It solved my problem.
I was checking the `window.location.href` via `WebViewBridge.send` . before it was returning `about:blank` but with this fix it returns the location properly and script injection works consistently.

Thanks!

**Comment by dfejgelis** [comment]
This isn't working for me either. 
I've used master + this PR and it still doesn't work after first load

**Comment by Naoto-Ida** [comment]
I still have the issue of `[INFO:CONSOLE(1)] "Uncaught ReferenceError: WebViewBridge is not defined", source:  (1)`.

I have page A, I login, then page B should give me back certain values.
Works on iOS, but doesn't on Android.
I copied the changes in the PR one to one, still doesn't solve it.

**Comment by MacKentoch** [comment]
@alinz please accept @magicismight PR.
It resolved my android issues that occured on 2nd load.

I guess it will resolve a lot of android issues.

**Comment by hmedney** [comment]
Indirectly fixed in PR #150; A variable named `WebViewBridgeAndroid` is no longer used.

**Pull request closed without merging**
