### PR TITLE
Fix iOS

### LINKED ISSUE #224: RCTViewManager   RCTView
image

### PR DESCRIPTION
**Pull request by ericmuyser**
Fixes #224 #219 #209 #213

### CODE REVIEW

**Comment by MagicIndustries** [comment]
Was just about to submit this PR myself - any chance of getting it merged in soon? without it this package is unusable with RN current

**Comment by alinz** [comment]
@MagicIndustries done!, send it over and will publish it to npm

**Comment by alinz** [comment]
@ericmuyser thanks

**Comment by MagicIndustries** [comment]
Nice one, thanks!

**Comment by alinz** [comment]
@MagicIndustries if you willing to help me, I can give you permission to access to merge as well?

**Comment by MagicIndustries** [comment]
@alinz Happy to help - but isn't this merged already now?

**Comment by alinz** [comment]
@MagicIndustries, what I meant was I wanted to add you as a main contributor for this project. I need someone to take care of PRs and taking care of issues.

**Pull request merged**
