### PR TITLE
Android support

### PR DESCRIPTION
**Pull request by jjshammas**

### CODE REVIEW

**Comment by alinz** [comment]
@jjshammas there are some conflicts with the master. would you try to see if you can fix those conflicts? if you won't let me know and I will do it myself. 

btw, thank for this! Awesome work!

**Comment by jjshammas** [comment]
@alinz unfortunately will not be able to take a look until mid-Feb…feel free to resolve if you can

**Comment by alinz** [comment]
@jjshammas Cool, I will, thanks!

**Comment by MacKentoch** [comment]
@jjshammas @alinz guys when this PR is resolved you will enter history :+1: 
I can't wait it!

**Comment by rmevans9** [comment]
@alinz how goes the updating?

**Comment by alinz** [comment]
@jjshammas thanks for your PR. It was an interesting approach you have taken, 

@MacKentoch, @rmevans9, I have updated project. Android version is in beta I need couple of more days to clean up the code and right more tests. but since everyone is waiting for it, I have decided to publish it in advance.

I'm closing this PR request. Again thank you @jjshammas.

**Pull request closed without merging**
