### PR TITLE
add fix for RN v0.31

### PR DESCRIPTION
**Pull request by JakeRawr**

### CODE REVIEW

**Comment by JakeRawr** [comment]
please merge this soon! Thanks

**Comment by philharton** [comment]
You're a lifesaver, thanks!

**Comment by dangnelson** [comment]
Are you not getting a "ReactNative.createClass' error after adding this fix?

**Comment by philharton** [comment]
@dangnelson I don't remember having done anything else to get it working on iOS but I did update the Android js interface to match RN's WebView more closely, as it seems to have changed a bit since this module was created. This version is working for me on iOS and Android with RN0.31: https://github.com/philharton/react-native-webview-bridge

There are some extra methods I added which you probably won't need but perhaps it can help you pin down the error you're seeing.

**Comment by philharton** [comment]
@dangnelson if you're talking Android, you may need to update some other stuff, and this may serve as a reference as it's what I'm using on Android with RN0.31: https://github.com/philharton/react-native-webview-bridge

If on iOS, I actually ended up using a modified version of this WkWebView module because it performs far better: https://github.com/CRAlpha/react-native-wkwebview

**Comment by hmedney** [comment]
Thanks for submitting this fix!

**Pull request merged**
