### PR TITLE
add retries for fetching from registry

### PR DESCRIPTION
**Pull request by boourns**
@alinz please review

I was hitting the issue in https://github.com/facebook/react-native/issues/2010 using react-native-0.9.0-rc last night and could not avoid the crash using `setTimeout` as a workaround in any shape or form.  I ended up adding a retry around the specific code that crashes in the two places i've reproduced a crash, and it's solved the issue for me.

Code's not pretty but I'm open to discussion.  This is also the first 10 lines of objective C i've ever written ;)

### CODE REVIEW

**Comment by alinz** [comment]
@boourns awesome!

One question though, does it happen only on `callbackCleanup`? if so, we might be able to fix this issue on JS instead.

**Comment by boourns** [comment]
@alinz Last night it was only happening on `callbackCleanup` but this morning it occurred in `onMessage` as well, so I applied the same fix and haven't been able to reproduce.... yet ;)

**Comment by alinz** [comment]
@boourns would you create a simple test case which causes this issue. I want to test mine!

**Comment by alinz** [comment]
I have found that usually it crashes in Simulator and I haven't seen crashes on device itself. have you seen happens in device itself?

**Comment by boourns** [comment]
Hey @alinz 

I rewrote my use-case to not need the bridge.

I actually only experienced the crash in simulator.  I did not try on device.

**Pull request closed without merging**
