### PR TITLE
Doesn't work with the `Create folder references` option

### PR DESCRIPTION
**Pull request by bryanlarsen**
So state that in the README.

### CODE REVIEW

**Comment by bryanlarsen** [comment]
Sorry, I cannot get it to work, so I'm unable to write instructions telling others how to install it.

I assumed that the new install instructions would basically be the same as https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

It appears that I got the installation correct, because I can build my project and instantiate a WebViewBridge.   However, the 'WebViewBridge' event never fires.

In my sample app, it gets to 'ready1', but not 'ready2'.

https://gist.github.com/bryanlarsen/43abd9fe91e02eb3dcfc

**Comment by bryanlarsen** [comment]
It appears that your Sample1 app is broken too, the "Hello this is me calling from web page" is never sent or received.

**Comment by alinz** [comment]
I will look into during the weekend. Thanks for feedback!

**Comment by bryanlarsen** [comment]
@alinz, did you get a chance to look at it?   I'm still using the rick-li PR in my project, which works fine with the old instructions.  That's fine for me, but we're probably limiting our user base by having the old instructions packaged with a version that installs quite differently.

**Comment by alinz** [comment]
@bryanlarsen I wnated to merge this one, but I have release a new version which will fixes this issue. Please have a look at it and let me know.

**Pull request closed without merging**
